server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    username: root
    password: root
    url: jdbc:mysql://${HOSTNAME}:3306/customerdb
    #url: jdbc:mysql://18.189.111.79:3306/customerdb  #this will connect the IDE(like STS) to dockerized mysql but a containerized jar will not
    #url: jdbc:mysql://localhost:3306/customerdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    show-sql: true
      